---
swagger: "2.0"
info:
  description: "API turmas"
  version: "1.0.0"
  title: "Swagger Turma"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "root"
basePath: "/"
tags:
- name: "turma"
  description: "Turma"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /turma:
    get:
      tags:
      - "turma"
      summary: "Get all"
      description: "Get all turmas"
      operationId: "getTurmas"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/getAllTurma"
      x-swagger-router-controller: "Turma"
  /turma/{turmaid}:
    get:
      tags:
      - "turma"
      summary: "Get turma by id"
      description: "Get turma by id"
      operationId: "getTurma"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "turmaid"
        in: "path"
        description: "ID of turma to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Turma"
      x-swagger-router-controller: "Turma"
  /turma/delete/{turmaid}:
    delete:
      tags:
      - "turma"
      summary: "Delete turma by id"
      description: "Delete turma by id"
      operationId: "deleteTurma"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "turmaid"
        in: "path"
        description: "ID of turma deleted to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Not found"
      x-swagger-router-controller: "Turma"
  /turma/update/{turmaid}:
    put:
      tags:
      - "turma"
      summary: "Update turma by id"
      description: "Update turma by id"
      operationId: "updateTurma"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "turmaid"
        in: "path"
        description: "turma"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated turma item object"
        required: true
        schema:
          $ref: "#/definitions/Turma"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Not found"
      x-swagger-router-controller: "Turma"
  /turma/create/:
    post:
      tags:
      - "turma"
      summary: "Create turma"
      description: "Create turma"
      operationId: "createTurma"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Create turma object"
        required: true
        schema:
          $ref: "#/definitions/Turma"
      responses:
        "201":
          description: "OK"
        "302":
          description: "Already exists"
      x-swagger-router-controller: "Turma"
  /turma/patch/{turmaid}:
    patch:
      tags:
      - "turma"
      summary: " Partially update turma by id"
      description: "Partially update turma by id"
      operationId: "PartiallyUpdateTurma"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "turmaid"
        in: "path"
        description: "turma"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated turma item object"
        required: false
        schema:
          $ref: "#/definitions/Turma"
      responses:
        "200":
          description: "OK"
        "404":
          description: "Not found"
      x-swagger-router-controller: "Turma"
definitions:
  getAllTurma:
    type: "array"
    items:
      $ref: "#/definitions/Turma"
  Turma:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      ano:
        type: "integer"
        format: "int64"
      semestre:
        type: "integer"
        format: "int64"
      turma:
        type: "integer"
        format: "int64"
      horario:
        type: "array"
        description: "Horario da turma"
        items:
          type: "object"
          properties: {}
    example:
      ano: 6
      horario:
      - "{}"
      - "{}"
      id: 0
      semestre: 1
      turma: 5
